{% set name = "catalystcoop.pudl" %}
{% set version = "2024.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1c202cd048ab5d4dbd70f70ef7b3b9057d4123d89d5404bec9ec10925d1a363

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ferc_to_sqlite = pudl.ferc_to_sqlite.cli:main
    - metadata_to_rst = pudl.convert.metadata_to_rst:metadata_to_rst
    - pudl_check_fks = pudl.etl.check_foreign_keys:pudl_check_fks
    - pudl_datastore = pudl.workspace.datastore:pudl_datastore
    - pudl_etl = pudl.etl.cli:pudl_etl
    - pudl_service_territories = pudl.analysis.service_territory:pudl_service_territories

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - setuptools_scm
  run:
    - python >=3.11,<3.12
    - addfips ==0.4.0
    - alembic ==1.13.1
    - boto3 ==1.34.34
    - bottleneck ==1.3.7
    - catalystcoop.dbfread ==3.0.0
    - catalystcoop.ferc_xbrl_extractor ==1.3.2
    - click ==8.1.7
    - coloredlogs ==14.0
    - conda-lock ==2.5.2
    - coverage ==7.4.1
    - dagster ==1.6.3
    - dagster-postgres ==0.22.3
    - dask ==2024.1.1
    - datasette ==0.64.6
    - doc8 ==1.1.1
    - email-validator ==2.1.0
    - frictionless ==4.40.8
    - fsspec ==2023.12.2
    - furo ==2024.1.29
    - gcsfs ==2023.12.2.post1
    - gdal ==3.8.3
    - geopandas ==0.14.3
    - grpcio ==1.60.0
    - grpcio-health-checking ==1.60.0
    - grpcio-status ==1.60.0
    - hypothesis ==6.97.4
    - jellyfish ==1.0.3
    - jinja2 ==3.1.3
    - jupyter
    - matplotlib-base ==3.8.2
    - nbconvert ==7.14.2
    - nbformat ==5.9.2
    - networkx ==3.2.1
    - numba ==0.58.1
    - numexpr ==2.8.8
    - numpy ==1.26.3
    - openpyxl ==3.1.2
    - packaging ==23.2
    - pandas ==2.1.4
    - pandera ==0.17.2
    - pre-commit ==3.6.0
    - pyarrow ==15.0.0
    - pydantic ==2.6.0
    - pydantic-settings ==2.1.0
    - pytest ==8.0.0
    - pytest-cov ==4.1.0
    - pytest-console-scripts ==1.4.1
    - pytest-mock ==3.12.0
    - pytest-xdist ==3.5.0
    - python-build ==1.0.3
    - python-dotenv ==1.0.1
    - pytz ==2024.1
    - pyxlsb ==1.0.10
    - pyyaml ==6.0.1
    - readthedocs-sphinx-ext ==2.2.5
    - regex ==2023.12.25
    - requests ==2.31.0
    - responses ==0.24.1
    - ruff ==0.2.0
    - scikit-learn ==1.4.0
    - scipy ==1.12.0
    - Shapely ==2.0.2
    - sphinx ==7.2.6
    - sphinx-autoapi ==3.0.0
    - sphinx-issues ==1.2.0
    - sphinx-reredirects ==0.1.2
    - sphinxcontrib-bibtex ==2.6.1
    - sqlalchemy ==2.0.25
    - sqlite ==3.44.2
    - timezonefinder ==6.3.0
    - universal_pathlib ==0.1.4
    - urllib3 ==1.26.18
    - xlrd ==2.0.1
    - xlsxwriter ==3.1.9

test:
  imports:
    - pudl
  commands:
    - ferc_to_sqlite --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - pudl_check_fks --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - pudl_service_territories --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
    - zschira
    - bendnorman
    - jdangerx
