{% set name = "catalystcoop.pudl" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab6925701b57625b67027fefa00639e12aad476dd7493383af527415a4115289

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - pudl_data = pudl.workspace.datastore_cli:main
    - pudl_setup = pudl.workspace.setup_cli:main
    - pudl_etl = pudl.cli:main
    - ferc1_to_sqlite = pudl.convert.ferc1_to_sqlite:main
    - epacems_to_parquet = pudl.convert.epacems_to_parquet:main
    - datapkg_to_sqlite = pudl.convert.datapkg_to_sqlite:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - setuptools
    - coloredlogs
    - datapackage >=1.9.0
    - dbfread
    - goodtables
    - matplotlib
    - networkx >=2.2
    - numpy
    - pandas >=0.24
    - pyarrow >=0.14.0
    - pyyaml
    - python-snappy
    - scikit-learn >=0.20
    - scipy
    - sqlalchemy >=1.3.0
    - tableschema
    - tableschema-sql >=1.1.0
    - timezonefinder
    - xlsxwriter

test:
  imports:
    - pudl
  commands:
    - pudl_setup
    - pudl_data --help > /dev/null
    - ferc1_to_sqlite --help > /dev/null
    - pudl_etl --help > /dev/null
    - datapkg_to_sqlite --help > /dev/null
    - epacems_to_parquet --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'An open data processing pipeline for public US utility data.'

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
