{% set name = "catalystcoop.pudl" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f4d5569f838a68bf42e688fb90d53a06d30afa70c62cbad4bf2d8b27daa200c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - censusdp1tract_to_sqlite = pudl.convert.censusdp1tract_to_sqlite:main
    - datapkg_to_rst = pudl.convert.datapkg_to_rst:main
    - datapkg_to_sqlite = pudl.convert.datapkg_to_sqlite:main
    - epacems_to_parquet = pudl.convert.epacems_to_parquet:main
    - ferc1_to_sqlite = pudl.convert.ferc1_to_sqlite:main
    - pudl_datastore = pudl.workspace.datastore:main
    - pudl_etl = pudl.cli:main
    - pudl_setup = pudl.workspace.setup_cli:main
    - pudl_territories = pudl.analysis.service_territory:main

requirements:
  host:
    - python >=3.8,<3.10
    - pip
    - setuptools_scm
  run:
    - python >=3.8,<3.10
    - addfips ~=0.3.1
    - catalystcoop.dbfread ~=3.0
    - coloredlogs ~=15.0
    - contextily ~=1.0
    - datapackage ~=1.11
    - fsspec ~=0.8.7
    - gcsfs ~=0.7.2
    - geopandas ~=0.9.0
    - goodtables-pandas-py ~=0.2.0
    - jinja2 ~=2.11
    - matplotlib-base ~=3.0
    - networkx ~=2.2
    - numpy ~=1.20
    - pandas ~=1.2.5
    - prefect >=14.2,<15.0
    - pyarrow ~=4.0
    - pygeos ~=0.9.0
    - python-snappy ~=0.6.0
    - pyyaml ~=5.0
    - scikit-learn ~=0.24.1
    - scipy ~=1.6
    - setuptools
    - sqlalchemy <1.4
    - tableschema ~=1.12
    - tableschema-sql ~=1.3
    - timezonefinder ~=5.0
    - xlsxwriter ~=1.3

test:
  imports:
    - pudl
  commands:
    - pudl_setup
    - censusdp1tract_to_sqlite --help > /dev/null
    - datapkg_to_rst --help > /dev/null
    - datapkg_to_sqlite --help > /dev/null
    - epacems_to_parquet --help > /dev/null
    - ferc1_to_sqlite --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - pudl_territories --help > /dev/null

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
