{% set name = "catalystcoop.pudl" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae38e0b451369d2de54c4a29bcd7778fdb9745105df2e2f02cec67a5081d4fd4

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - censusdp1tract_to_sqlite = pudl.convert.censusdp1tract_to_sqlite:main
    - metadata_to_rst = pudl.convert.metadata_to_rst:main
    - epacems_to_parquet = pudl.convert.epacems_to_parquet:main
    - ferc1_to_sqlite = pudl.convert.ferc1_to_sqlite:main
    - pudl_datastore = pudl.workspace.datastore:main
    - pudl_etl = pudl.cli:main
    - pudl_setup = pudl.workspace.setup_cli:main
    - state_demand = pudl.analysis.state_demand:main

requirements:
  host:
    - python >=3.8,<3.10
    - pip
    - setuptools_scm
  run:
    - python >=3.8,<3.10
    - addfips ~=0.3.1
    - catalystcoop.dbfread ~=3.0
    - coloredlogs ~=15.0
    - datapackage ~=1.11
    - email-validator >=1.0.3  # pydantic email extra
    - fsspec ~=2021.7
    - gcsfs ~=2021.7
    - geopandas >=0.9,<0.11
    - google-cloud-bigquery >=1.6.0,<2.0 # prefect google extra
    - google-cloud-secret-manager >2.4.0 # prefect google extra
    - google-cloud-storage >=1.13,<2.0   # prefect google extra
    - graphviz >0.8.3 # prefect viz extra
    - jinja2 ~=3.0
    - matplotlib-base ~=3.0
    - networkx ~=2.2
    - numpy ~=1.20
    - pandas ~=1.3,!=1.3.3
    - prefect ~=0.15
    - pyarrow >=5,<7
    - pydantic ~=1.7
    - pygeos >=0.10,<0.12
    - python-snappy ~=0.6.0
    - pyyaml >=5,<7
    - scikit-learn ~=1.0
    - scipy ~=1.6
    - setuptools
    - sqlalchemy ~=1.4
    - timezonefinder ~=5.0
    - xlsxwriter ~=3.0

test:
  imports:
    - pudl
  commands:
    - pudl_setup --clobber
    - censusdp1tract_to_sqlite --help > /dev/null
    - metadata_to_rst --help > /dev/null
    - epacems_to_parquet --help > /dev/null
    - ferc1_to_sqlite --help > /dev/null
    - pudl_datastore --help > /dev/null
    - pudl_etl --help > /dev/null
    - state_demand --help > /dev/null
    - pudl_etl --clobber settings/etl_fast.yml

about:
  home: https://catalyst.coop/pudl
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open data processing pipeline for public US utility data.

  description: |
    The PUDL (Public Utility Data Liberation) project extracts electric
    utility data from US government sources, standardizes it, and integrates
    it for easier use by researchers, activists, journalists, and others
    working in the public interest. It includes data from EIA forms 860 and
    923, FERC form 1, EPA CEMS hourly, and other sources.

  doc_url: https://catalystcoop-pudl.readthedocs.io/
  dev_url: https://github.com/catalyst-cooperative/pudl

extra:
  recipe-maintainers:
    - zaneselvans
