travis:
  secure:
    BINSTAR_TOKEN: aEzDocIMb+o7vGhv9ptSNlR1FigJO+xdmZNWFOrJTwSZcmQy/E8T14awLQ3M7ttYeLveInWlbYSd1soAyCWR3lqnbD4LKA6MUA0pcW/45Z4sZR+zuXLb7zRNJWSBys7Ebl8CFvca4IGiK8r/wwyvmrzkJC8kP1KwNtudgJ66krh3tDdCggNCpC8lsgtk+Gy2HLVeyK5DbhEtYHNYP6knQ5niJHRzBoI3Ln5lBcNu+o4ul3jkrNDM1uHgEIntSQ9mVHqhsoJTuscrnDzMXjFaYuJZ7tzd68OZr+mtCuABisG5OH459hFNGAPspWterl9euWihxJBpcuTu4pJWl8YCSbK3uA1nBlSYX19m+w/HnPqsLrNJH/WoYlsRyBdeTOqraorY/DqZduF8mHeDsYt+KRWZ7fr3CrXMWXIR0NA8vcqcxbU0rQZkU0QdEHO0kc0WlcXzM4SUJf6RoLraLnJUi10bFX7ZajKW++wf1NW6qmyJNe8tGIxzualTQClrC+bmwNoWsjE7prtvHILB2s9UUlYBy8D1HqDZHr/cvCkwUNDO1fsLoW67DhQGAKlXd4GCDykhOQ8iINpnOCMsonZaq9RvFeIpMQzDJ/Bq67tfLIJA6QoqAkW9aC0SnEauuESMQg80gMUU6B8+6OyGVwjI5x2Wbn1Uf5ebwm38DP37W9k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
